name: CronJob

on: 
  schedule: 
    - cron: "0 7 * * *" # every day at 7am

jobs:
  job:
    runs-on: ubuntu-latest
    environment:
      name: "<environment-name>"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Run app
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: echo "Hello from cron job"
